apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ymd 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ymd 
    spec:
      containers:
        - name: ymd 
          image: ymdreg.azurecr.io/ymd
          ports:
          - containerPort: 80